name: 'Runner Label Resolver'
description: 'Resolve labels of an organization-level runner'
author: 'Jussi Vatjus-Anttila'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
outputs:
  labels:
    description: 'Labels of the runner'
runs:
  using: 'node20'
  main: 'dist/index.js'
